apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuup-pod2
  labels:
    app: my-name2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-name2
  template:
    metadata:
      labels:
        app: my-name2
    spec:
      containers:
        - name: cpu-container2
          image: nogisora/pod2-image:latest
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: cpuup-service2
  labels:
    app: my-name2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32000
  selector:
    app: my-name2
