apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuup-pod3
  labels:
    app: my-name3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-name3
  template:
    metadata:
      labels:
        app: my-name3
    spec:
      containers:
        - name: cpu-container3
          image: nogisora/pod3-image:latest
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cpuup-service3
  labels:
    app: my-name3
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500
  selector:
    app: my-name3
